// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izqyuooxblumhdhudunh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cXl1b294Ymx1bWhkaHVkdW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTUwMzIsImV4cCI6MjA2NTIzMTAzMn0.LtS32EyYkcm2dUancr0eSMEzRPsrWifGomGXwMk6QGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);